### ISSUE TITLE
process_reports.py is missing

### ISSUE THREAD

**Issue by bugbaba** [projectrecon/hackerone_wordlist#1]
Hey,

I just stumbled on this repository, the idea of getting wordlist from h1 reports looks interesting.
Would you care to share `process_reports.py` file.

--
Regards,
@bugbaba

**Comment by xyele** [comment]
Hey! Sorry for late, I went a short break of developing the project a time ago. It is not finished yet, working on it. It will be released at this repo (private for now): https://github.com/xyele/hackerone_wordlist

Also here is my tweets about the project.
https://twitter.com/zeroxyele/status/1274655517122715649

I'm appreciated for your interest. Keep following it please.
